version: '2'

services:
  backend:
    
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8000:8000'

    env_file: 
      - .env
        
    command: ["./activate.sh"]
    
  