version: '2'

services:
  detector:
    
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8000:8000'
    
    volumes:
      - '.:/api'
    
    command: ["./activate.sh"]
  